<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
    <PackageVersion Include="Azure.Security.KeyVault.Secrets" Version="4.7.0" />
    <PackageVersion Include="SuperOffice.Crm.Online.IntegrationServices" Version="10.5.5.982" />
    <PackageVersion Include="SuperOffice.Online.Tokens" Version="7.21.0" />
    <PackageVersion Include="EPPlus" Version="6.1.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
    <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
    <PackageVersion Include="System.Diagnostics.EventLog" Version="8.0.2" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageVersion Include="System.ServiceModel.Primitives" Version="8.1.2" />
    <PackageVersion Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    <PackageVersion Include="CoreWCF.Http" Version="1.9.1" />
    <PackageVersion Include="CoreWCF.Primitives" Version="1.9.1" />
    <PackageVersion Include="NSwag.AspNetCore" Version="14.7.1" />
    <PackageVersion Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.19.1" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="8.0.4" />
  </ItemGroup>
</Project>